name: Bug Report
description: File a bug report
labels: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! 
        
        Before submitting please check existing issues for duplicates and [troubleshooting page](https://github.com/kaiusl/KLPlugins.DynLeaderboards/wiki/Troubleshooting) in the wiki for knwown issues.
        Also turn on Log option in the plugin settings menu and reproduce the issue. This will produce more detailed log file which will hopefully help to figure out the problem faster.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      description: What version of this plugin are you using?
    validations:
      required: true
  - type: input
    id: simhub_version
    attributes:
      label: SimHub version
      description: What version of SimHub are you running?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Before posting turn on Log option in the plugin settings menu and reproduce the issue. 
        Attach the log file generated by the SimHub. Located in SimHub/Logs.
  - type: textarea
    id: extra_info
    attributes:
      label: Extra information
      description: A screenshot, a custom dashboard, a custom leaderboard config (located in SimHub\PluginsData\KLPlugins\DynLeaderboards\leaderboardConfigs) or anything else you might think that may helps to figure out the issue.
